services:
  - type: web
    name: forex-course-platform
    runtime: image
    repo: https://github.com/Ahmedhla/forex-course-platform
    branch: master
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d7d3ldn41pts739pq70g-a/forex_course_db?ssl=true&sslmode=require
      - key: DB_USERNAME
        value: forex_user
      - key: DB_PASSWORD
        value: t1NNWeRauAF7sKUQEPdjlsxhYKiAOXUR
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JWT_SECRET
        value: MySuperSecretKeyForJWT2024ForexPlatform
      - key: PORT
        value: 8080